Disable rM build for now

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -130,70 +130,70 @@ jobs:
           name: rmufuse-alpine
           path: dist
           if-no-files-found: error
-  build-executable-remarkable:
-    name: Build binary for reMarkable
-    needs: [test]
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout the Git repository
-        uses: actions/checkout@v6
-      - uses: actions/setup-python@v6
-        with:
-          python-version: "3.11"
-          cache: "pip"
-      - name: Nuitka ccache
-        uses: actions/cache@v5
-        with:
-          path: ${{ github.workspace }}/.nuitka
-          key: ${{ github.job }}-ccache-remarkable-2.15.1
-      - name: Set up QEMU
-        uses: docker/setup-qemu-action@v3
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v3
-      - name: Build with nuitka
-        run: |
-          set -e
-          ./make_for_remarkable.sh portable \
-          | while read -r line; do
-            if [[ "$line" == 'Nuitka'*':ERROR:'* ]] || [[ "$line" == "ERROR:"* ]]; then
-              echo "::error file=${{ steps.args.outputs.main_file }},title=Nuitka Error::$line"
-            elif [[ "$line" == 'Nuitka'*':WARNING:'* ]] || [[ "$line" == "WARNING:"* ]]; then
-              echo "::warning file=${{ steps.args.outputs.main_file }},title=Nuitka Warning::$line"
-            elif [[ "$line" == 'Nuitka:INFO:'* ]] || [[ "$line" == "INFO:"* ]]; then
-              echo "$line"
-            else
-              echo "::debug::$line"
-            fi
-          done
-          sudo mv dist/rmufuse-portable dist/rmufuse-remarkable
-        working-directory: ${{ github.workspace }}
-      - uses: actions/upload-artifact@v6
-        with:
-          name: rmufuse-remarkable
-          path: dist
-          if-no-files-found: error
-      - name: Free up space
-        run: |
-          export DEBIAN_FRONTEND="noninteractive"
-          sudo apt-get autoremove -y
-          sudo apt-get autoclean -y
-          sudo rm -rf \
-            /usr/lib/jvm \
-            /usr/share/dotnet \
-            /usr/share/swift \
-            /usr/local/.ghcup \
-            /usr/local/julia* \
-            /usr/local/lib/android \
-            /usr/local/share/chromium \
-            /opt/microsoft /opt/google \
-            /opt/az \
-            /usr/local/share/powershell
-      - name: Sanity check
-        uses: Eeems-Org/run-in-remarkable-action@v1
-        with:
-          fw_version: 2.15.1
-          run: ./rmufuse-remarkable --help
-          path: dist
+  # build-executable-remarkable:
+  #   name: Build binary for reMarkable
+  #   needs: [test]
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Checkout the Git repository
+  #       uses: actions/checkout@v6
+  #     - uses: actions/setup-python@v6
+  #       with:
+  #         python-version: "3.11"
+  #         cache: "pip"
+  #     - name: Nuitka ccache
+  #       uses: actions/cache@v5
+  #       with:
+  #         path: ${{ github.workspace }}/.nuitka
+  #         key: ${{ github.job }}-ccache-remarkable-2.15.1
+  #     - name: Set up QEMU
+  #       uses: docker/setup-qemu-action@v3
+  #     - name: Set up Docker Buildx
+  #       uses: docker/setup-buildx-action@v3
+  #     - name: Build with nuitka
+  #       run: |
+  #         set -e
+  #         ./make_for_remarkable.sh portable \
+  #         | while read -r line; do
+  #           if [[ "$line" == 'Nuitka'*':ERROR:'* ]] || [[ "$line" == "ERROR:"* ]]; then
+  #             echo "::error file=${{ steps.args.outputs.main_file }},title=Nuitka Error::$line"
+  #           elif [[ "$line" == 'Nuitka'*':WARNING:'* ]] || [[ "$line" == "WARNING:"* ]]; then
+  #             echo "::warning file=${{ steps.args.outputs.main_file }},title=Nuitka Warning::$line"
+  #           elif [[ "$line" == 'Nuitka:INFO:'* ]] || [[ "$line" == "INFO:"* ]]; then
+  #             echo "$line"
+  #           else
+  #             echo "::debug::$line"
+  #           fi
+  #         done
+  #         sudo mv dist/rmufuse-portable dist/rmufuse-remarkable
+  #       working-directory: ${{ github.workspace }}
+  #     - uses: actions/upload-artifact@v6
+  #       with:
+  #         name: rmufuse-remarkable
+  #         path: dist
+  #         if-no-files-found: error
+  #     - name: Free up space
+  #       run: |
+  #         export DEBIAN_FRONTEND="noninteractive"
+  #         sudo apt-get autoremove -y
+  #         sudo apt-get autoclean -y
+  #         sudo rm -rf \
+  #           /usr/lib/jvm \
+  #           /usr/share/dotnet \
+  #           /usr/share/swift \
+  #           /usr/local/.ghcup \
+  #           /usr/local/julia* \
+  #           /usr/local/lib/android \
+  #           /usr/local/share/chromium \
+  #           /opt/microsoft /opt/google \
+  #           /opt/az \
+  #           /usr/local/share/powershell
+  #     - name: Sanity check
+  #       uses: Eeems-Org/run-in-remarkable-action@v1
+  #       with:
+  #         fw_version: 2.15.1
+  #         run: ./rmufuse-remarkable --help
+  #         path: dist
   build-wheel:
     name: Build wheel with python ${{ matrix.python }}
     needs: [test]
@@ -302,7 +302,7 @@ jobs:
     needs:
       - build-executable-ubuntu
       - build-executable-alpine
-      - build-executable-remarkable
+      # - build-executable-remarkable
       - build-wheel
       - build-any-wheel
       - build-sdist
