Update to remarkable-update-image 1.3.3 (#19)
* Update to remarkable-update-image 1.3.3

* Add missing lint job

* Use venv for build, add missing dependencies

* Add issing license info

* use native-wheel for install

* Add missing rmufuse release upload

* Add back using extra-index for builds

* Don't fail fast

* Add extra-index-url where missing

* Review feedback

* Swap to my apt cache action

* Avoid name conflicts for executables

* Add fuse-devel

* Fix build

* Review feedback

* Permissions fix

* Cleanup

* Disable rM build for now

* Fix name

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -9,31 +9,42 @@ on:
     types: [released]
 permissions: read-all
 jobs:
+  lint:
+    name: Lint
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout the Git repository
+        uses: actions/checkout@v6
+      - uses: actions/setup-python@v6
+        with:
+          python-version: "3.11"
+          cache: "pip"
+      - name: Lint code
+        run: make lint format
   test:
     name: Test with python ${{ matrix.python }}
     runs-on: ubuntu-latest
     strategy:
       matrix:
-        python:
+        python: &python-versions
           - "3.11"
           - "3.12"
           - "3.13"
+      fail-fast: false
     steps:
       - name: Install Apt packages
         id: cache-apt
-        uses: awalsh128/cache-apt-pkgs-action@latest
+        uses: Eeems-Org/apt-cache-action@v1
         with:
-          execute_install_scripts: true
           packages: libfuse-dev
-          version: 1.0
       - name: Checkout the Git repository
-        uses: actions/checkout@v4
-      - uses: actions/setup-python@v5
+        uses: actions/checkout@v6
+      - uses: actions/setup-python@v6
         with:
           python-version: ${{ matrix.python }}
           cache: "pip"
       - name: Cache test files
-        uses: actions/cache@v4
+        uses: actions/cache@v5
         with:
           path: |
             .venv/bin/codexctl.bin
@@ -49,28 +60,30 @@ jobs:
       matrix:
         python:
           - "3.11"
+      fail-fast: false
     steps:
       - name: Install Apt packages
         id: cache-apt
-        uses: awalsh128/cache-apt-pkgs-action@latest
+        uses: Eeems-Org/apt-cache-action@v1
         with:
-          execute_install_scripts: true
           packages: libfuse-dev ccache
-          version: 1.0
       - name: Checkout the Git repository
-        uses: actions/checkout@v4
-      - uses: actions/setup-python@v5
+        uses: actions/checkout@v6
+      - uses: actions/setup-python@v6
         with:
           python-version: ${{ matrix.python }}
           cache: "pip"
       - name: Nuitka ccache
-        uses: actions/cache@v4
+        uses: actions/cache@v5
         with:
           path: ${{ github.workspace }}/.nuitka
           key: ${{ github.job }}-ccache-ubuntu-latest
       - name: Build with nuitka
-        run: make executable
-      - uses: actions/upload-artifact@v4
+        run: |
+          set -e
+          make executable
+          mv dist/rmufuse dist/rmufuse-ubuntu
+      - uses: actions/upload-artifact@v6
         with:
           name: rmufuse-ubuntu
           path: dist
@@ -83,9 +96,10 @@ jobs:
       matrix:
         alpine:
           - v3.19
+      fail-fast: false
     steps:
       - name: Checkout the Git repository
-        uses: actions/checkout@v4
+        uses: actions/checkout@v6
       - uses: jirutka/setup-alpine@v1
         with:
           branch: ${{ matrix.alpine }}
@@ -101,97 +115,98 @@ jobs:
             patchelf
             upx
       - name: Nuitka ccache
-        uses: actions/cache@v4
+        uses: actions/cache@v5
         with:
           path: ${{ github.workspace }}/.nuitka
           key: ${{ github.job }}-ccache-alpine-${{ matrix.alpine }}
       - name: Build with nuitka
         shell: alpine.sh {0}
         run: |
+          set -e
           make executable
-      - uses: actions/upload-artifact@v4
+          mv dist/rmufuse dist/rmufuse-alpine
+      - uses: actions/upload-artifact@v6
         with:
           name: rmufuse-alpine
           path: dist
           if-no-files-found: error
-  build-executable-remarkable:
-    name: Build binary for reMarkable
-    needs: [test]
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout the Git repository
-        uses: actions/checkout@v4
-      - uses: actions/setup-python@v5
-        with:
-          python-version: "3.11"
-          cache: "pip"
-      - name: Nuitka ccache
-        uses: actions/cache@v4
-        with:
-          path: ${{ github.workspace }}/.nuitka
-          key: ${{ github.job }}-ccache-remarkable-2.15.1
-      - name: Set up QEMU
-        uses: docker/setup-qemu-action@v3
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v3
-      - name: Build with nuitka
-        run: |
-          set -e
-          ./make_for_remarkable.sh portable \
-          | while read -r line; do
-            if [[ "$line" == 'Nuitka'*':ERROR:'* ]] || [[ "$line" == "ERROR:"* ]]; then
-              echo "::error file=${{ steps.args.outputs.main_file }},title=Nuitka Error::$line"
-            elif [[ "$line" == 'Nuitka'*':WARNING:'* ]] || [[ "$line" == "WARNING:"* ]]; then
-              echo "::warning file=${{ steps.args.outputs.main_file }},title=Nuitka Warning::$line"
-            elif [[ "$line" == 'Nuitka:INFO:'* ]] || [[ "$line" == "INFO:"* ]]; then
-              echo "$line"
-            else
-              echo "::debug::$line"
-            fi
-          done
-        working-directory: ${{ github.workspace }}
-      - uses: actions/upload-artifact@v4
-        with:
-          name: rmufuse-remarkable
-          path: dist
-          if-no-files-found: error
-      - name: Free up space
-        run: |
-          export DEBIAN_FRONTEND="noninteractive"
-          sudo apt-get autoremove -y
-          sudo apt-get autoclean -y
-          sudo rm -rf \
-            /usr/lib/jvm \
-            /usr/share/dotnet \
-            /usr/share/swift \
-            /usr/local/.ghcup \
-            /usr/local/julia* \
-            /usr/local/lib/android \
-            /usr/local/share/chromium \
-            /opt/microsoft /opt/google \
-            /opt/az \
-            /usr/local/share/powershell
-      - name: Sanity check
-        uses: Eeems-Org/run-in-remarkable-action@v1
-        with:
-          fw_version: 2.15.1
-          run: ./rmufuse-portable --help
-          path: dist
+  # build-executable-remarkable:
+  #   name: Build binary for reMarkable
+  #   needs: [test]
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Checkout the Git repository
+  #       uses: actions/checkout@v6
+  #     - uses: actions/setup-python@v6
+  #       with:
+  #         python-version: "3.11"
+  #         cache: "pip"
+  #     - name: Nuitka ccache
+  #       uses: actions/cache@v5
+  #       with:
+  #         path: ${{ github.workspace }}/.nuitka
+  #         key: ${{ github.job }}-ccache-remarkable-2.15.1
+  #     - name: Set up QEMU
+  #       uses: docker/setup-qemu-action@v3
+  #     - name: Set up Docker Buildx
+  #       uses: docker/setup-buildx-action@v3
+  #     - name: Build with nuitka
+  #       run: |
+  #         set -e
+  #         ./make_for_remarkable.sh portable \
+  #         | while read -r line; do
+  #           if [[ "$line" == 'Nuitka'*':ERROR:'* ]] || [[ "$line" == "ERROR:"* ]]; then
+  #             echo "::error file=${{ steps.args.outputs.main_file }},title=Nuitka Error::$line"
+  #           elif [[ "$line" == 'Nuitka'*':WARNING:'* ]] || [[ "$line" == "WARNING:"* ]]; then
+  #             echo "::warning file=${{ steps.args.outputs.main_file }},title=Nuitka Warning::$line"
+  #           elif [[ "$line" == 'Nuitka:INFO:'* ]] || [[ "$line" == "INFO:"* ]]; then
+  #             echo "$line"
+  #           else
+  #             echo "::debug::$line"
+  #           fi
+  #         done
+  #         sudo mv dist/rmufuse-portable dist/rmufuse-remarkable
+  #       working-directory: ${{ github.workspace }}
+  #     - uses: actions/upload-artifact@v6
+  #       with:
+  #         name: rmufuse-remarkable
+  #         path: dist
+  #         if-no-files-found: error
+  #     - name: Free up space
+  #       run: |
+  #         export DEBIAN_FRONTEND="noninteractive"
+  #         sudo apt-get autoremove -y
+  #         sudo apt-get autoclean -y
+  #         sudo rm -rf \
+  #           /usr/lib/jvm \
+  #           /usr/share/dotnet \
+  #           /usr/share/swift \
+  #           /usr/local/.ghcup \
+  #           /usr/local/julia* \
+  #           /usr/local/lib/android \
+  #           /usr/local/share/chromium \
+  #           /opt/microsoft /opt/google \
+  #           /opt/az \
+  #           /usr/local/share/powershell
+  #     - name: Sanity check
+  #       uses: Eeems-Org/run-in-remarkable-action@v1
+  #       with:
+  #         fw_version: 2.15.1
+  #         run: ./rmufuse-remarkable --help
+  #         path: dist
   build-wheel:
     name: Build wheel with python ${{ matrix.python }}
     needs: [test]
     runs-on: ubuntu-latest
     strategy:
       matrix:
-        python:
-          - "3.11"
-          - "3.12"
-          - "3.13"
+        python: *python-versions
+      fail-fast: false
     steps:
       - name: Checkout the Git repository
-        uses: actions/checkout@v4
+        uses: actions/checkout@v6
       - name: Setup Python
-        uses: actions/setup-python@v5
+        uses: actions/setup-python@v6
         with:
           python-version: ${{ matrix.python }}
           cache: "pip"
@@ -200,19 +215,41 @@ jobs:
           python_version=${{ matrix.python }}
           python_version=cp${python_version//.}
           script=$(cat <<EOF
+          dnf -y install fuse-devel
           cd /src;
           export PATH=\$PATH:/opt/python/$python_version-$python_version/bin;
-          make ${{ env.FLAGS }} wheel;
+          make native-wheel;
           auditwheel repair dist/*.whl;
           EOF
           )
-          docker run -v $(pwd):/src \
+          docker run \
+            --rm \
+            --volume=$(pwd):/src \
             quay.io/pypa/manylinux_2_34_x86_64:latest \
             /bin/bash -c "$script"
-      - uses: actions/upload-artifact@v4
+      - uses: actions/upload-artifact@v6
         with:
           name: pip-wheel-${{ matrix.python }}
           path: wheelhouse/*
+          if-no-files-found: error
+  build-any-wheel:
+    name: Build wheel
+    runs-on: ubuntu-latest
+    needs: [test, lint]
+    steps:
+      - name: Checkout the Git repository
+        uses: actions/checkout@v6
+      - name: Setup Python
+        uses: actions/setup-python@v6
+        with:
+          python-version: "3.11"
+          cache: "pip"
+      - name: Building package
+        run: make wheel
+      - uses: actions/upload-artifact@v6
+        with:
+          name: pip-wheel-none-any
+          path: dist/*
           if-no-files-found: error
   build-sdist:
     name: Build sdist
@@ -220,17 +257,15 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout the Git repository
-        uses: actions/checkout@v4
+        uses: actions/checkout@v6
       - name: Setup Python
-        uses: actions/setup-python@v5
+        uses: actions/setup-python@v6
         with:
           python-version: "3.11"
           cache: "pip"
-      - name: Install build tool
-        run: pip install build
       - name: Building package
         run: make sdist
-      - uses: actions/upload-artifact@v4
+      - uses: actions/upload-artifact@v6
         with:
           name: pip-sdist
           path: dist/*
@@ -241,14 +276,8 @@ jobs:
     needs:
       - build-sdist
       - build-wheel
+      - build-any-wheel
     runs-on: ubuntu-latest
-    strategy:
-      matrix:
-        artifact:
-          - "pip-sdist"
-          - "pip-wheel-3.11"
-          - "pip-wheel-3.12"
-          - "pip-wheel-3.13"
     permissions:
       id-token: write
       contents: write
@@ -258,59 +287,52 @@ jobs:
     steps:
       - name: Download pip packages
         id: download
-        uses: actions/download-artifact@v4
+        uses: actions/download-artifact@v8
         with:
-          name: ${{ matrix.artifact }}
+          pattern: pip-*
+          merge-multiple: true
       - name: Publish package distributions to PyPI
         uses: pypa/gh-action-pypi-publish@release/v1
         with:
           packages-dir: ${{ steps.download.outputs.download-path }}
           skip-existing: true
   release:
-    name: Add ${{ matrix.artifact }} to release
+    name: Add files to release
     if: github.repository == 'Eeems-Org/remarkable-update-fuse' && github.event_name == 'release' && startsWith(github.ref, 'refs/tags')
     needs:
       - build-executable-ubuntu
       - build-executable-alpine
-      - build-executable-remarkable
+      # - build-executable-remarkable
       - build-wheel
+      - build-any-wheel
       - build-sdist
     runs-on: ubuntu-latest
-    strategy:
-      matrix:
-        artifact:
-          - "rmufuse-ubuntu"
-          - "rmufuse-alpine"
-          - "rmufuse-remarkable"
-          - "pip-sdist"
-          - "pip-wheel-3.11"
-          - "pip-wheel-3.12"
-          - "pip-wheel-3.13"
     permissions:
       contents: write
     steps:
       - name: Checkout the Git repository
-        uses: actions/checkout@v4
-      - name: Download executable
-        id: download
-        uses: actions/download-artifact@v4
+        uses: actions/checkout@v6
+      - name: Download pip packages
+        id: packages
+        uses: actions/download-artifact@v8
         with:
-          name: ${{ matrix.artifact }}
-          path: dist
-      - name: Upload to release
-        run: |
-          if [ -f rmufuse ]; then
-            name="rmufuse-${{ matrix.artifact }}"
-            mv rmufuse "$name"
-            gh release upload "$TAG" "$name" --clobber
-          elif [ -f rmufuse-portable ]; then
-            name="rmufuse-${{ matrix.artifact }}"
-            mv rmufuse-portable "$name"
-            gh release upload "$TAG" "$name" --clobber
-          else
-            find . -type f | xargs -rI {} gh release upload "$TAG" {} --clobber
-          fi
+          pattern: pip-*
+          merge-multiple: true
+      - name: Download executables
+        id: executables
+        uses: actions/download-artifact@v8
+        with:
+          pattern: rmufuse-*
+          merge-multiple: true
+      - name: Upload pip packages to release
+        run: find . -type f | xargs -rI {} gh release upload "$TAG" {} --clobber
         env:
           GH_TOKEN: ${{ github.token }}
           TAG: ${{ github.event.release.tag_name }}
-        working-directory: ${{ steps.download.outputs.download-path }}
+        working-directory: ${{ steps.packages.outputs.download-path }}
+      - name: Upload executables to release
+        run: find . -type f | xargs -rI {} gh release upload "$TAG" {} --clobber
+        env:
+          GH_TOKEN: ${{ github.token }}
+          TAG: ${{ github.event.release.tag_name }}
+        working-directory: ${{ steps.executables.outputs.download-path }}
